package com.ai.commithelper.prompt;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Structured commit message generated by the model.
 *
 * @author AI Commit Helper
 * @since 1.0.0
 */
public class CommitMessageResult {

    private final String title;
    private final List<String> items;

    public CommitMessageResult(String title, List<String> items) {
        this.title = title == null ? "" : title.trim();
        this.items = cleanItems(items);
    }

    public String getTitle() {
        return title;
    }

    public List<String> getItems() {
        return Collections.unmodifiableList(items);
    }

    /**
     * Renders the final commit message inserted into IDEA.
     *
     * @return formatted commit message
     */
    public String format() {
        StringBuilder builder = new StringBuilder();
        builder.append(title.isEmpty() ? "更新代码改动" : title).append("\n\n");
        for (String item : items) {
            builder.append("- ").append(item).append('\n');
        }
        return builder.toString().trim();
    }

    private static List<String> cleanItems(List<String> source) {
        List<String> result = new ArrayList<>();
        if (source != null) {
            for (String item : source) {
                if (item != null && !item.trim().isEmpty()) {
                    result.add(stripBullet(item.trim()));
                }
            }
        }
        if (result.isEmpty()) {
            result.add("总结本次代码改动");
        }
        return result;
    }

    private static String stripBullet(String value) {
        while (value.startsWith("-") || value.startsWith("*") || value.startsWith("•")) {
            value = value.substring(1).trim();
        }
        return value;
    }
}
